.PHONY: build
build:	
	javac -d . Input.java Main.java Printer.java Tasks.java 

.PHONY: run
run:	
	java -classpath . Main

.PHONY: execute
execute:	
	javac -d . Input.java Main.java Printer.java Tasks.java
	java by.bntu.fitr.alex.javalabs.lab07.control.Main	

.DEFAULT_GOAL := execute
